# Generated by Django 3.0.4 on 2020-04-16 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200325_1618'),
        ('dlc', '0002_coursegroup_courseitem_courseliter_coursepo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('work', models.IntegerField(default=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dlc.Course')),
            ],
        ),
        migrations.CreateModel(
            name='TeachGroupStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Students')),
                ('teach_groop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dlc.TeachGroup')),
            ],
        ),
    ]
