# Generated by Django 3.0.4 on 2020-04-23 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dlc', '0004_auto_20200416_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='TeachPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('theme', models.CharField(max_length=150)),
                ('time1', models.CharField(max_length=10)),
                ('time2', models.CharField(max_length=10)),
                ('descrip', models.CharField(max_length=150)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dlc.Sections')),
                ('teach_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dlc.TeachGroup')),
            ],
        ),
    ]
