# Generated by Django 3.0.4 on 2020-04-25 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200325_1618'),
        ('dlc', '0006_visited_visitedstudents'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=45)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('price', models.IntegerField(default=0)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Persons')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Students')),
                ('teach_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dlc.TeachGroup')),
            ],
        ),
    ]
