# Generated by Django 3.0.4 on 2020-05-02 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dlc', '0007_contract'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teachgroup',
            options={'managed': False},
        ),
    ]
