# Generated by Django 3.0.4 on 2020-05-02 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200325_1618'),
        ('dlc', '0008_auto_20200502_1644'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='teachgroup',
            table='dlc_teachgroup',
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
    ]
