# Generated by Django 3.0.4 on 2020-05-05 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dlc', '0009_auto_20200502_2306'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visited',
            options={'managed': False},
        ),
    ]
