# Generated by Django 3.0.3 on 2020-03-13 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_students'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='auth_user',
        ),
    ]
