# Generated by Django 3.0.4 on 2020-03-18 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('second_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('date_bitrh', models.DateField()),
                ('adress', models.CharField(max_length=150)),
                ('document_type', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=100)),
                ('data_documentp', models.CharField(max_length=45)),
                ('phone', models.CharField(max_length=20)),
                ('inn', models.CharField(max_length=22)),
                ('status', models.CharField(max_length=50)),
                ('seria', models.CharField(max_length=5)),
                ('numberp', models.CharField(max_length=7)),
                ('given', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'persons',
                'managed': False,
            },
        ),
    ]
