# Generated by Django 3.0.4 on 2020-03-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200323_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('second_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('position', models.CharField(max_length=45)),
                ('work', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'employee',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='persons',
            table='persons',
        ),
    ]
