export const GET_USERS = "GET_USERS"


export const GET_STUDENTS = "GET_STUDENTS"
export const DELETE_STUDENT = "DELETE_STUDENT"
export const PUT_STUDENT = "PUT_STUDENT"
export const ADD_STUDENT = "ADD_STUDENT"

export const GET_PLACE = "GET_PLACE"
export const DELETE_PLACE = "DELETE_PLACE"
export const PUT_PLACE = "PUT_PLACE"
export const ADD_PLACE = "ADD_PLACE"

export const GET_PERSONS = "GET_PERSONS"
export const DELETE_PERSONS = "DELETE_PERSONS"
export const PUT_PERSONS = "PUT_PERSONS"
export const ADD_PERSONS = "ADD_PERSONS"

export const GET_EMPLOYERS = "GET_EMPLOYERS"
export const DELETE_EMPLOYER = "DELETE_EMPLOYER"
export const PUT_EMPLOYER = "PUT_EMPLOYER"
export const ADD_EMPLOYER = "ADD_EMPLOYER"

export const GET_COURSES = "GET_COURSES"
export const DELETE_COURSE = "DELETE_COURSE"
export const PUT_COURSE = "PUT_COURSE"
export const ADD_COURSE = "ADD_COURSE"

export const GET_COURSE_GROUP = "GET_COURSE_GROUP"
export const DELETE_COURSE_GROUP = "DELETE_COURSE_GROUP"
export const PUT_COURSE_GROUP = "PUT_COURSE_GROUP"
export const ADD_COURSE_GROUP = "ADD_COURSE_GROUP"

export const GET_COURSE_PO = "GET_COURSE_PO"
export const DELETE_COURSE_PO = "DELETE_COURSE_PO"
export const PUT_COURSE_PO = "PUT_COURSE_PO"
export const ADD_COURSE_PO = "ADD_COURSE_PO"

export const GET_COURSE_LITER = "GET_COURSE_LITER"
export const DELETE_COURSE_LITER = "DELETE_COURSE_LITER"
export const PUT_COURSE_LITER = "PUT_COURSE_LITER"
export const ADD_COURSE_LITER = "ADD_COURSE_LITER"

export const GET_COURSE_ITEM = "GET_COURSE_ITEM"
export const DELETE_COURSE_ITEM = "DELETE_COURSE_ITEM"
export const PUT_COURSE_ITEM = "PUT_COURSE_ITEM"
export const ADD_COURSE_ITEM = "ADD_COURSE_ITEM"

export const GET_TEACHGROUP = "GET_TEACHGROUP"
export const DELETE_TEACHGROUP = "DELETE_TEACHGROUP"
export const PUT_TEACHGROUP = "PUT_TEACHGROUP"
export const ADD_TEACHGROUP = "ADD_TEACHGROUP"

export const GET_TEACHGROUPSTUDENT = "GET_TEACHGROUPSTUDENT"
export const DELETE_TEACHGROUPSTUDENT = "DELETE_TEACHGROUPSTUDENT"
export const PUT_TEACHGROUPSTUDENT = "PUT_TEACHGROUPSTUDENT"
export const ADD_TEACHGROUPSTUDENT = "ADD_TEACHGROUPSTUDENT"

export const GET_SECTIONS = "GET_SECTIONS"
export const DELETE_SECTIONS = "DELETE_SECTIONS"
export const PUT_SECTIONS = "PUT_SECTIONS"
export const ADD_SECTIONS = "ADD_SECTIONS"

export const GET_TEACHPLAN = "GET_TEACHPLAN"
export const DELETE_TEACHPLAN = "DELETE_TEACHPLAN"
export const PUT_TEACHPLAN = "PUT_TEACHPLAN"
export const ADD_TEACHPLAN = "ADD_TEACHPLAN"

export const GET_VISITED = "GET_VISITED"
export const DELETE_VISITED = "DELETE_VISITED"
export const PUT_VISITED = "PUT_VISITED"
export const ADD_VISITED = "ADD_VISITED"

export const GET_VISITEDSTUDENTS = "GET_VISITEDSTUDENTS"
export const DELETE_VISITEDSTUDENTS = "DELETE_VISITEDSTUDENTS"
export const PUT_VISITEDSTUDENTS = "PUT_VISITEDSTUDENTS"
export const ADD_VISITEDSTUDENTS = "ADD_VISITEDSTUDENTS"

export const GET_CONTRACT = "GET_CONTRACT"
export const DELETE_CONTRACT = "DELETE_CONTRACT"
export const PUT_CONTRACT = "PUT_CONTRACT"
export const ADD_CONTRACT = "ADD_CONTRACT"

export const GET_MESSAGE = "GET_MESSAGE"
export const ADD_MESSAGE = "ADD_MESSAGE"

export const GET_ERRORS = "GET_ERRORS"
export const CREATE_MESSAGE = "CREATE_MESSAGE"
export const USER_LOADING = "USER_LOADING"
export const USER_LOADED = "USER_LOADED"
export const AUTH_ERROR = "AUTH_ERROR"
export const LOGIN_ADMIN_SUCCESS = "LOGIN_ADMIN_SUCCESS"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAIL = "REGISTER_FAIL"